# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 895389447a3e0931c4a62a70c098266b5f45cbbba276e8cf49694475dcbd8c6d372906c5f9f35fb6abce2c296aa600756a5c0b265c124a80cf136dbdb6deaba9

test:
  secret_key_base: 175a974d7097d160b1e426e89fbb6024c3a2d487e2ce98d1361b34dbf419b22640d1c864288ad5ef995bfd602074489a43bd1a3674b3bbd6260d74e011b94ce2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
